---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

# Reproducible Research: Peer Assessment 1

## Introduction

It is now possible to collect a large amount of data about personal
movement using activity monitoring devices such as a
[Fitbit](http://www.fitbit.com), [Nike
Fuelband](http://www.nike.com/us/en_us/c/nikeplus-fuelband), or
[Jawbone Up](https://jawbone.com/up). These type of devices are part of
the "quantified self" movement -- a group of enthusiasts who take
measurements about themselves regularly to improve their health, to
find patterns in their behavior, or because they are tech geeks. But
these data remain under-utilized both because the raw data are hard to
obtain and there is a lack of statistical methods and software for
processing and interpreting the data.

This assignment makes use of data from a personal activity monitoring
device. This device collects data at 5 minute intervals through out the
day. The data consists of two months of data from an anonymous
individual collected during the months of October and November, 2012
and include the number of steps taken in 5 minute intervals each day.

## Data

The data for this assignment can be downloaded from the course web site:

Dataset: Activity monitoring data [52K]
The variables included in this dataset are:

  **steps**: Number of steps taking in a 5-minute interval (missing values are coded as NA)

  **date**: The date on which the measurement was taken in YYYY-MM-DD format  

  **interval**: Identifier for the 5-minute interval in which measurement was taken

The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations in this dataset.


## Loading and preprocessing the data

``` {r loading data}
data <- read.csv("activity.csv")
str(data)
```
There was no transformation of the data needed. The data is stored in a dataframe called 'data'. The dataframe consist of 17,568 observations of 3 variables: 'steps', 'date', 'interval'.

## What is mean total number of steps taken per day?

The mean number of steps is derived by creating a dataframe called 'steps.per.day'.

``` {creating mean dataframe}
library (plyr)
steps.per.day<-ddply(data, .(date), summarize,total=sum(steps,na.rm=TRUE))
str(steps.per.day)
```

'steps.per.day' is a dataframe of 61 observations in 2 variables: 'date' and 'total'.

The total number of steps per day can be graphically shown in the following manner:

``` {plotting bar chart of total steps per day}
library(ggplot2)

cl <- colors() #colors is a vector containing the color palete
par(ps=10, mar=c(3.1,2.1,6.1,2.1), fg="blue4",col.lab="violetred4", col.main="violetred4", col.axis="violetred4", bg=cl[431])
barplot(steps.per.day$total,main="Total Steps per Day", xlab="Day", ylab="Total Steps", names.arg=steps.per.day$date)
```

The mean and median of the daily number of steps can be computed in the following manner:

```{mean & median}
daily.mean <- mean(steps.per.day$total)
daily.median <- median(steps.per.day$total)
```

The daily mean steps is 9,354.23. 
The daily median steps is 10,395.

## What is the average daily activity pattern?

The average computed across each 3-minute interval and across all days can be computed by subsetting a new dataframe using 'data$interval' and summarized by mean.

```{getting mean for the 5-min intervals}
avg.steps.per.interval<- ddply (data, .(interval), summarize, avg.steps=mean(steps, na.rm=TRUE))
str(avg.steps.per.interval)
```

The resulting dataframe has 288 observations in 2 variables: 'interval' and 'avg.steps'.

The time series plot of the Average number of steps per day over all the 5-min intervals can be done in the following manner.

```{}
g<-ggplot (avg.steps.per.interval, aes(x=interval, y=avg.steps)) + geom_line() +labs(x="Interval", y="Average Steps per Interval", title="Plot of Average Steps per Intervals" )
print (g)
```

To find the Interval where the maximum number of steps occur, we can do the following.

```{which max did it occur}
avg.steps.per.interval$interval[which.max(avg.steps.per.interval$avg.steps)]
```

The corresponding maximum number of steps can be found from the follwoing.

```{}
avg.steps.per.interval$avg.steps[which.max(avg.steps.per.interval$avg.steps)]
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
